name: Update Content from Google Docs

on:
  schedule:
    - cron: '0 11 * * 1,4'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Ensures full repo history for rebase

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run script
        run: node ./js/fetch-google.js
        env:
          NODE_ENV: production
      
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Ensure the data directory exists
          mkdir -p ./data/
          
          # Add all changes, including new and deleted files
          git add -A

          # Check if there are any changes before committing
          if ! git diff --cached --quiet; then
            git commit -m "Auto update data files"
            git pull --rebase
            git push origin HEAD:${GITHUB_REF}
          else
            echo "No changes to commit."
          fi

      - name: Trigger Deploy Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
